/*
 * Decompiled with CFR 0.145.
 */
package dev.recollect.hana.api.utils.dev;

import dev.recollect.hana.mod.modules.impl.combat.dev.hanacry.ObsidianHelper;
import dev.recollect.hana.xibao.xibaoutil.RenderHelper;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class UI {
    public static JLabel label14;
    public static JLabel label15;
    public static JLabel label12;
    public static JFrame frame;
    public static JPanel panel1;
    public static JLabel label18;
    public static JLabel label4;
    public static JLabel label2;
    public static JLabel label8;
    public static JLabel label11;
    public static JLabel label21;
    public static JLabel label1;
    public static JButton button1;
    public static JLabel label9;
    public static JPanel panel4;
    public static JLabel label6;
    public static JLabel label17;
    public static JLabel label19;
    public static JPanel panel3;
    public static JLabel label5;
    public static JTextField textField1;
    public static JLabel label7;
    public static JLabel label20;
    public static JLabel label3;
    public static JLabel label10;
    public static JLabel label13;
    public static JLabel label16;
    public static JPanel panel2;

    public UI() {
        UI a;
    }

    static {
        panel1 = new JPanel();
        panel2 = new JPanel();
        label1 = new JLabel();
        label2 = new JLabel();
        panel3 = new JPanel();
        label3 = new JLabel();
        label4 = new JLabel();
        label5 = new JLabel();
        label6 = new JLabel();
        label7 = new JLabel();
        label8 = new JLabel();
        label9 = new JLabel();
        label10 = new JLabel();
        label11 = new JLabel();
        label12 = new JLabel();
        textField1 = new JTextField();
        button1 = new JButton();
        panel4 = new JPanel();
        label13 = new JLabel();
        label14 = new JLabel();
        label15 = new JLabel();
        label16 = new JLabel();
        label17 = new JLabel();
        label18 = new JLabel();
        label19 = new JLabel();
        label20 = new JLabel();
        label21 = new JLabel();
        frame = new JFrame();
    }

    public static void Load(String a) {
        Rectangle rectangle;
        String string = a;
        frame.setAlwaysOnTop(true);
        frame.setBackground(new Color(15461355));
        frame.setForeground(Color.white);
        frame.setTitle(RenderHelper.ALLATORIxDEMO("\u9aee\u8bdc\u7a6c\u5e97"));
        Container container = frame.getContentPane();
        container.setLayout(null);
        panel1.setBackground(new Color(15539236));
        panel1.setLayout(null);
        panel2.setBackground(Color.white);
        panel2.setLayout(null);
        panel1.add(panel2);
        panel2.setBounds(240, 50, 145, 5);
        label1.setText(ObsidianHelper.ALLATORIxDEMO("\u9a95\u8bb3\u7a0e\u5ee1"));
        label1.setForeground(Color.white);
        label1.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 35));
        label1.setHorizontalAlignment(0);
        panel1.add(label1);
        label1.setBounds(225, 0, 175, 55);
        label2.setText(ObsidianHelper.ALLATORIxDEMO("Q\u0013k\u000f"));
        label2.setForeground(Color.white);
        label2.setFont(label2.getFont().deriveFont((float)label2.getFont().getSize() + 5.0f));
        label2.setHorizontalAlignment(0);
        panel1.add(label2);
        label2.setBounds(235, 55, 155, UI.label2.getPreferredSize().height);
        a = new Dimension();
        int n = 0;
        int n2 = n;
        while (n2 < panel1.getComponentCount()) {
            rectangle = panel1.getComponent(n).getBounds();
            ((Dimension)a).width = Math.max(rectangle.x + rectangle.width, ((Dimension)a).width);
            ((Dimension)a).height = Math.max(rectangle.y + rectangle.height, ((Dimension)a).height);
            n2 = ++n;
        }
        Insets insets = panel1.getInsets();
        Object object = a;
        ((Dimension)object).width += insets.right;
        ((Dimension)object).height += insets.bottom;
        panel1.setMinimumSize((Dimension)a);
        panel1.setPreferredSize((Dimension)a);
        container.add(panel1);
        panel1.setBounds(0, 0, 640, 110);
        panel3.setBackground(Color.white);
        panel3.setLayout(null);
        label3.setText(RenderHelper.ALLATORIxDEMO(")"));
        label3.setForeground(new Color(12829635));
        label3.setFont(label3.getFont().deriveFont((float)label3.getFont().getSize() + 25.0f));
        label3.setHorizontalAlignment(0);
        panel3.add(label3);
        label3.setBounds(new Rectangle(new Point(55, 30), label3.getPreferredSize()));
        label4.setText(ObsidianHelper.ALLATORIxDEMO("\u6883\u67cc\u4f22\u76be\u7f00\u7ebe\uff05\u7877\u4faf\u4f65\u76ea"));
        label4.setForeground(new Color(12829635));
        label4.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 15));
        panel3.add(label4);
        label4.setBounds(75, 35, 180, 20);
        label5.setText(ObsidianHelper.ALLATORIxDEMO("\u7f48\u7eae\u7540\u9074"));
        label5.setForeground(new Color(12829635));
        label5.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 15));
        panel3.add(label5);
        label5.setBounds(new Rectangle(new Point(75, 55), label5.getPreferredSize()));
        label6.setText(ObsidianHelper.ALLATORIxDEMO("\\"));
        label6.setFont(label6.getFont().deriveFont((float)label6.getFont().getSize() + 25.0f));
        label6.setForeground(new Color(12829635));
        panel3.add(label6);
        label6.setBounds(new Rectangle(new Point(400, 30), label6.getPreferredSize()));
        label7.setText(RenderHelper.ALLATORIxDEMO("\u6cb2\u676b\u537c\u5ba1'"));
        label7.setFont(new Font(ObsidianHelper.ALLATORIxDEMO("m\"\\&\rzG%]bc0*lpRP'"), 0, 15));
        label7.setForeground(new Color(12829635));
        panel3.add(label7);
        label7.setBounds(new Rectangle(new Point(425, 35), label7.getPreferredSize()));
        label8.setText(RenderHelper.ALLATORIxDEMO("\u8bc7\u6212\u5f13\u53b3\u8018\u83d0\u53ce"));
        label8.setForeground(new Color(12829635));
        label8.setFont(new Font(ObsidianHelper.ALLATORIxDEMO("m\"\\&\rzG%]bc0*lpRP'"), 0, 15));
        panel3.add(label8);
        label8.setBounds(new Rectangle(new Point(425, 55), label8.getPreferredSize()));
        label9.setText(RenderHelper.ALLATORIxDEMO("+"));
        label9.setFont(label9.getFont().deriveFont((float)label9.getFont().getSize() + 25.0f));
        label9.setForeground(new Color(12829635));
        panel3.add(label9);
        label9.setBounds(new Rectangle(new Point(55, 125), label9.getPreferredSize()));
        label10.setText(ObsidianHelper.ALLATORIxDEMO("\u5279\u5ef3\u6080\u76c7\u9aa5\u8b83\u4fdb\u603eN\u6835\u5f16\u59f0\u4e0eT"));
        label10.setForeground(new Color(12829635));
        label10.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 15));
        panel3.add(label10);
        label10.setBounds(new Rectangle(new Point(75, 120), label10.getPreferredSize()));
        label11.setText(ObsidianHelper.ALLATORIxDEMO("[H!U$Q+\u00103\u0019\u0007k\u0016w\u0000a\u0006zy2H{\u0010~\rh\u0015OJ]9@7"));
        label11.setForeground(new Color(12829635));
        label11.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 12));
        panel3.add(label11);
        label11.setBounds(new Rectangle(new Point(75, 140), label11.getPreferredSize()));
        label12.setText(ObsidianHelper.ALLATORIxDEMO("u=_:Kt\u0000\u001el\u00110Gi\u000eloj\u00101ZN=W*"));
        label12.setForeground(new Color(12829635));
        label12.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 12));
        panel3.add(label12);
        label12.setBounds(new Rectangle(new Point(75, 160), label12.getPreferredSize()));
        label19.setText(ObsidianHelper.ALLATORIxDEMO("Z"));
        label19.setFont(label19.getFont().deriveFont((float)label19.getFont().getSize() + 25.0f));
        label19.setForeground(new Color(12829635));
        panel3.add(label19);
        label19.setBounds(new Rectangle(new Point(400, 125), label19.getPreferredSize()));
        label20.setText(RenderHelper.ALLATORIxDEMO("\u8bde\u7228\u8b85\u60e7\u76b4\u7544\u6224\u546f\u5491\u5ba1\u7819"));
        label20.setForeground(new Color(12829635));
        label20.setFont(new Font(ObsidianHelper.ALLATORIxDEMO("m\"\\&\rzG%]bc0*lpRP'"), 0, 15));
        panel3.add(label20);
        label20.setBounds(new Rectangle(new Point(425, 130), label20.getPreferredSize()));
        label21.setText(RenderHelper.ALLATORIxDEMO("\u5e46\u4e61\u8992\u5428\u8bd4\u4eb1\u4ea2"));
        label21.setForeground(new Color(12829635));
        label21.setFont(new Font(ObsidianHelper.ALLATORIxDEMO("m\"\\&\rzG%]bc0*lpRP'"), 0, 15));
        panel3.add(label21);
        label21.setBounds(new Rectangle(new Point(425, 150), label21.getPreferredSize()));
        textField1.setForeground(Color.white);
        textField1.setEditable(true);
        textField1.setFont(textField1.getFont().deriveFont((float)textField1.getFont().getSize() + 1.0f));
        textField1.setText(string);
        textField1.setBackground(new Color(12829635));
        panel3.add(textField1);
        textField1.setBounds(200, 190, 240, UI.textField1.getPreferredSize().height);
        textField1.requestFocusInWindow();
        button1.setText(RenderHelper.ALLATORIxDEMO("\u6cfb\u51ee2\u761c\u5f4d"));
        button1.setFont(new Font(ObsidianHelper.ALLATORIxDEMO("m\"\\&\rzG%]bc0*lpRP'"), 1, 15));
        button1.setBackground(Color.decode(RenderHelper.ALLATORIxDEMO("H\u000f \u0001.\u0004+")));
        button1.setFocusPainted(false);
        button1.setForeground(Color.white);
        panel3.add(button1);
        button1.setBounds(new Rectangle(new Point(260, 230), button1.getPreferredSize()));
        a = new Dimension();
        int n3 = 0;
        int n4 = n3;
        while (n4 < panel3.getComponentCount()) {
            rectangle = panel3.getComponent(n3).getBounds();
            ((Dimension)a).width = Math.max(rectangle.x + rectangle.width, ((Dimension)a).width);
            ((Dimension)a).height = Math.max(rectangle.y + rectangle.height, ((Dimension)a).height);
            n4 = ++n3;
        }
        insets = panel3.getInsets();
        Object object2 = a;
        ((Dimension)object2).width += insets.right;
        ((Dimension)object2).height += insets.bottom;
        panel3.setMinimumSize((Dimension)a);
        panel3.setPreferredSize((Dimension)a);
        container.add(panel3);
        panel3.setBounds(0, 110, 640, 270);
        panel4.setBackground(new Color(15461355));
        panel4.setLayout(null);
        label13.setText(ObsidianHelper.ALLATORIxDEMO("\u8bfc\u56bc\u780e\u89b2\u9aee\u8bc8\u53f6\u808f\u4f1fT"));
        label13.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 1, 13));
        panel4.add(label13);
        label13.setBounds(new Rectangle(new Point(30, 0), label13.getPreferredSize()));
        label14.setText(ObsidianHelper.ALLATORIxDEMO("8\u0006\u4f23\u76ad\u9ace\u8bfb\u4fb0\u600d\u88a2\u6c21\u4e37\u5c04\u79ef"));
        label14.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 13));
        panel4.add(label14);
        label14.setBounds(30, 20, 160, UI.label14.getPreferredSize().height);
        label15.setText(ObsidianHelper.ALLATORIxDEMO(";\u0006\u53ac\u7218\u76c6\u7c49\u5916\u644e\u516c\u4f79\u76f6\u7530\u817f"));
        label15.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 13));
        panel4.add(label15);
        label15.setBounds(30, 40, 200, UI.label15.getPreferredSize().height);
        label16.setText(ObsidianHelper.ALLATORIxDEMO("\u59c0\u67a6\u8f88\u664d\u4e09\u4e33\u956b\u8beaT"));
        label16.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 1, 13));
        panel4.add(label16);
        label16.setBounds(new Rectangle(new Point(395, 0), label16.getPreferredSize()));
        label17.setText(ObsidianHelper.ALLATORIxDEMO("r\u0007\u8bb5\u7af1\u526a\u5473\u5f09\u53c8\u8077\u6c42\u62cb"));
        label17.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 13));
        panel4.add(label17);
        label17.setBounds(395, 20, 140, 15);
        label18.setText(ObsidianHelper.ALLATORIxDEMO("p\u0014\u6891\u6787\u8ba8\u7b8e\u6748\u8bbb\u7f00"));
        label18.setFont(new Font(RenderHelper.ALLATORIxDEMO("+p\u0016xB!9O>\u0015\u0016Q$v\u000b=2Q"), 0, 13));
        panel4.add(label18);
        label18.setBounds(new Rectangle(new Point(395, 40), label18.getPreferredSize()));
        a = new Dimension();
        n3 = 0;
        int n5 = n3;
        while (n5 < panel4.getComponentCount()) {
            rectangle = panel4.getComponent(n3).getBounds();
            ((Dimension)a).width = Math.max(rectangle.x + rectangle.width, ((Dimension)a).width);
            ((Dimension)a).height = Math.max(rectangle.y + rectangle.height, ((Dimension)a).height);
            n5 = ++n3;
        }
        insets = panel4.getInsets();
        Container container2 = container;
        Object object3 = a;
        ((Dimension)object3).width += insets.right;
        ((Dimension)object3).height += insets.bottom;
        panel4.setMinimumSize((Dimension)a);
        panel4.setPreferredSize((Dimension)a);
        container2.add(panel4);
        panel4.setBounds(0, 380, 640, 85);
        Object object4 = a = new Dimension();
        ((Dimension)object4).width = 640;
        ((Dimension)object4).height = 465;
        ((JComponent)container2).setMinimumSize((Dimension)a);
        ((JComponent)container).setPreferredSize((Dimension)a);
        frame.pack();
        frame.setLocationRelativeTo(frame.getOwner());
        frame.setResizable(false);
        frame.setVisible(true);
    }
}
